"""empty message

Revision ID: 2f89861d56e3
Revises: ffd3742ece3d
Create Date: 2019-12-10 15:59:06.897360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f89861d56e3'
down_revision = 'ffd3742ece3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('time_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('properties', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('category', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_table('categories')
    # ### end Alembic commands ###
