"""empty message

Revision ID: 77fe33128282
Revises: 136d61138b5e
Create Date: 2020-07-13 09:38:19.581069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fe33128282'
down_revision = '136d61138b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('time_added', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'time_added')
    # ### end Alembic commands ###
