"""empty message

Revision ID: 7ad0a341b2be
Revises: bd5dd3f4f08f
Create Date: 2020-08-17 10:04:56.467590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad0a341b2be'
down_revision = 'bd5dd3f4f08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
