"""empty message

Revision ID: b2d9a126302a
Revises: ea915579a9dd
Create Date: 2020-07-10 17:01:00.025542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d9a126302a'
down_revision = 'ea915579a9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('properties_agent_id_fkey', 'properties', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('properties_agent_id_fkey', 'properties', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###
