"""empty message

Revision ID: ba5779202626
Revises: c04302398f6d
Create Date: 2020-07-11 09:32:52.791091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5779202626'
down_revision = 'c04302398f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('del_hash', sa.String(length=155), nullable=True))
    op.add_column('photos', sa.Column('image', sa.String(length=255), nullable=True))
    op.drop_column('photos', 'photo_5')
    op.drop_column('photos', 'photo_4')
    op.drop_column('photos', 'photo_1')
    op.drop_column('photos', 'photo_3')
    op.drop_column('photos', 'photo_2')
    op.drop_column('photos', 'photo_6')
    op.drop_column('photos', 'photo_7')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('photo_7', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('photo_6', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('photo_2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('photo_3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('photo_1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('photo_4', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('photo_5', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('photos', 'image')
    op.drop_column('photos', 'del_hash')
    # ### end Alembic commands ###
