"""empty message

Revision ID: bcd155f8b0d1
Revises: 2f89861d56e3
Create Date: 2019-12-10 16:02:59.921192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd155f8b0d1'
down_revision = '2f89861d56e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'properties', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'category_id')
    # ### end Alembic commands ###
