"""empty message

Revision ID: bd5dd3f4f08f
Revises: 0b20f85953df
Create Date: 2020-08-17 10:04:33.812488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5dd3f4f08f'
down_revision = '0b20f85953df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'thumbnail')
    op.drop_column('users', 'thub_del_hash')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('thub_del_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('thumbnail', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
