"""empty message

Revision ID: c04302398f6d
Revises: b2d9a126302a
Create Date: 2020-07-10 18:54:55.997217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04302398f6d'
down_revision = 'b2d9a126302a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('properties', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('long', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'long')
    op.drop_column('properties', 'lat')
    op.drop_column('properties', 'address')
    # ### end Alembic commands ###
