"""empty message

Revision ID: ea915579a9dd
Revises: 6fd3f832786b
Create Date: 2020-07-10 16:51:15.275646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea915579a9dd'
down_revision = '6fd3f832786b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('price_offer', sa.String(length=155), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'price_offer')
    # ### end Alembic commands ###
